// <auto-generated />
namespace SocialMedia.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class mig0212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig0212));
        
        string IMigrationMetadata.Id
        {
            get { return "202102121250298_mig0212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
